datasets:
  - habitat
tasks:
  - open_cabinet
  - recognize_room
models:
  - kind: gpt
    n_frames: 5
  - kind: encoder
    encoder: clip
    head: cosine
    n_frames: 32
  - kind: encoder
    encoder: viclip
    head: cosine
  - kind: encoder
    encoder: s3d
    head: cosine
# Optional
task_path: tasks
video_path: videos
output_path: experiments