task_dir: tasks/habitat
video_dir: videos/habitat
tasks:
  - open_cabinet
models:
  - kind: encoder
    encoder: viclip
    heads:
      - kind: cosine
    batch_size: 1
  - kind: encoder
    encoder: s3d
    heads:
      - kind: cosine
  # - kind: encoder
  #   encoder: clip
  #   heads:
  #     - kind: cosine
  #   hf_model: ViT-bigG-14/laion2b_s39b_b160k
  #   n_frames: 32
  # - kind: gpt
  #   n_frames: 5