tasks:
  - closed_or_closing/cabinet
  - closed_or_closing/drawer
  - closed_or_closing/fridge
  - container_type/apple
  - container_type/can
  - container_type/hammer
  - near_or_far/chair
  - near_or_far/plant
  - near_or_far/tv
  - object/large_in_room
  - object/large
  - object/small_in_container
  - object/small
  - open_or_closed/cabinet
  - open_or_closed/drawer
  - open_or_closed/fridge
  - open_or_opening/cabinet
  - open_or_opening/drawer
  - open_or_opening/fridge
  - opening_or_closing/cabinet
  - opening_or_closing/container
  - opening_or_closing/drawer
  - opening_or_closing/fridge
  - room/find
  - room/model
  - room/scan
  - room/sequence
  - move_can
models:
  - kind: encoder
    encoder: clip
    heads:
      - kind: cosine
    hf_model: ViT-bigG-14/laion2b_s39b_b160k
    n_frames: 8
  - kind: encoder
    encoder: viclip
    heads:
      - kind: cosine
    batch_size: 16
  - kind: encoder
    encoder: s3d
    heads:
      - kind: cosine
task_dir: /data/datasets/vlm_benchmark/tasks/habitat
video_dir: /data/datasets/vlm_benchmark/videos/habitat