tasks:
  - break
  - combat
  - craft
  - find
  - mine
  - pickup
  - place
models:
  - kind: gpt
    n_frames: 10
    task_mode: multilabel
  - kind: encoder
    encoder: viclip
    heads:
      - kind: cosine
    batch_size: 16
  - kind: encoder
    encoder: s3d
    heads:
      - kind: cosine
task_dir: tasks/minecraft
video_dir: "."
cache_dir: .cache
output_dir: experiments