tasks:
  - multilabel
models:
  - kind: encoder
    encoder: s3d
    heads:
      - kind: cosine
    batch_size: 2
  - kind: encoder
    encoder: viclip
    heads:
      - kind: cosine
    batch_size: 16
task_dir: tasks/minecraft
video_dir: "."
cache_dir: .cache
output_dir: experiments