tasks:
  - recognize_cabinet_state_orig
  - recognize_container_state
  - recognize_drawer_state_orig
  - recognize_fridge_state_A
  - recognize_fridge_state_B
  - recognize_fridge_state_orig
models:
  - kind: encoder
    encoder: clip
    heads:
      - kind: cosine
    hf_model: ViT-bigG-14/laion2b_s39b_b160k
    n_frames: 4
  - kind: encoder
    encoder: viclip
    heads:
      - kind: cosine
  - kind: encoder
    encoder: s3d
    heads:
      - kind: cosine
task_dir: /data/datasets/vlm_benchmark/tasks/opening
video_dir: /data/datasets/vlm_benchmark/videos/habitat