models:
- async_batch: false
  is_one_shot: true
  kind: gpt
  model: gpt-4o
  n_frames: 16
tasks:
- level_2/remix/remix_level_2_group_1
- level_2/remix/remix_level_2_group_2
- level_2/remix/remix_level_2_group_3
- level_3/remix/remix_level_3_group_1
- level_3/remix/remix_level_3_group_2
# - level_2/permutation/permutation_level_2_group_1
# - level_2/permutation/permutation_level_2_group_2
# - level_2/permutation/permutation_level_2_group_3
# - level_2/permutation/permutation_level_2_group_4
# - level_2/permutation/permutation_level_2_group_5
# - level_2/permutation/permutation_level_2_group_6
# - level_2/permutation/permutation_level_2_group_7
# - level_2/permutation/permutation_level_2_group_8
# - level_3/permutation/permutation_level_3_group_1
# - level_3/permutation/permutation_level_3_group_2
# - level_3/permutation/permutation_level_3_group_3
# - level_3/permutation/permutation_level_3_group_4
# - level_3/permutation/permutation_level_3_group_5
# - level_3/permutation/permutation_level_3_group_6
# - level_3/permutation/permutation_level_3_group_7
# - level_3/permutation/permutation_level_3_group_8
# - level_5/permutation/permutation_level_5_group_1
# - level_5/permutation/permutation_level_5_group_2
# - level_5/permutation/permutation_level_5_group_3
# - level_5/permutation/permutation_level_5_group_4
# - level_5/permutation/permutation_level_5_group_5
#!! NOTE MISSING
- level_5/permutation/permutation_level_5_group_7
- level_8/permutation/permutation_level_8_group_1
#!! NOTE MISSING
- level_8/permutation/permutation_level_8_group_3
- level_8/permutation/permutation_level_8_group_4
task_dir: /data/datasets/vlm_benchmark/tasks/real_life
video_dir: /data/datasets/vlm_benchmark/videos/real_life
cache_dir: /data/datasets/vlm_benchmark/.cache
output_dir: /data/datasets/vlm_benchmark/experiments/evan
