models:
# - async_batch: false
#   is_one_shot: true
#   kind: gpt
#   model: gpt-4o
#   n_frames: 16
# - async_batch: false
#   is_one_shot: false
#   kind: gpt
#   model: gpt-4o
#   n_frames: 16
# - async_batch: false
#   is_one_shot: false
#   kind: gpt
#   model: gpt-4o
#   n_frames: 5
- encoder: s3d
  heads:
  - kind: cosine
  kind: encoder
- encoder: viclip
  heads:
  - kind: cosine
  kind: encoder
# - encoder: clip
#   heads:
#   - kind: cosine
#   hf_model: ViT-bigG-14/laion2b_s39b_b160k
#   kind: encoder
#   n_frames: 4
- batch_size: 1
  encoder: clip
  heads:
  - kind: cosine
  hf_model: ViT-bigG-14/laion2b_s39b_b160k
  kind: encoder
  n_frames: 32
tasks:
# - extrapyramidal/object_tracking - not completed
# - extrapyramidal/opening_and_closing
- extrapyramidal/object/recognize_small_object
# - foundation/clean/apple
# - foundation/clean/mug
# - foundation/containers/apple
# - foundation/containers/butter_knife
# - foundation/containers/can
# - foundation/containers/hammer
# - foundation/containers/mug
- foundation/cool/apple
- foundation/cool/mug
- foundation/heat/apple
- foundation/heat/mug
# - foundation/objects/pick_from_counter_top - not completed
# - foundation/objects/pick_from_dining_table - not completed
- foundation/on_v_off/desk_lamp
- foundation/on_v_off/faucet
- foundation/on_v_off/floor_lamp
- foundation/on_v_off/microwave
# - foundation/pick_v_put/fork - not completed
# - foundation/pick_v_put other - not completed
- foundation/toggle/desk_lamp
- foundation/toggle/faucet
- foundation/toggle/floor_lamp
- foundation/toggle/microwave
- foundation/slice/apple
- foundation/slice/potato
# - foundation/sliced_v_whole/apple
# - foundation/sliced_v_whole/potato
# - level_2/permutation/... - not completed
# - level_3/permutation/... - not completed
# - level_4/permutation/... - not completed
# - level_5/permutation/... - not completed
# - level_6/permutation/... - not completed
# - level_7/permutation/... - not completed
# - level_8/permutation/... - not completed
# - level_2/remix/... - not completed
# - level_3/remix/... - not completed
# - level_4/remix/... - not completed
# - level_5/remix/... - not completed
# - level_6/remix/... - not completed
# - level_7/remix/... - not completed
# - level_8/remix/... - not completed
task_dir: /data/datasets/vlm_benchmark/tasks/real_life
video_dir: /data/datasets/vlm_benchmark/videos/real_life
cache_dir: /data/datasets/vlm_benchmark/.cache
output_dir: /data/datasets/vlm_benchmark/experiments/evan