models:
# - async_batch: false
#   is_one_shot: true
#   kind: gpt
#   model: gpt-4o
#   n_frames: 16
# - async_batch: false
#   is_one_shot: false
#   kind: gpt
#   model: gpt-4o
#   n_frames: 16
# - async_batch: false
#   is_one_shot: false
#   kind: gpt
#   model: gpt-4o
#   n_frames: 5
- encoder: s3d
  heads:
  - kind: cosine
  kind: encoder
- encoder: viclip
  heads:
  - kind: cosine
  kind: encoder
# - encoder: clip
#   heads:
#   - kind: cosine
#   hf_model: ViT-bigG-14/laion2b_s39b_b160k
#   kind: encoder
#   n_frames: 4
- batch_size: 1
  encoder: clip
  heads:
  - kind: cosine
  hf_model: ViT-bigG-14/laion2b_s39b_b160k
  kind: encoder
  n_frames: 32
tasks:
# - extrapyramidal/object_tracking - not completed
# - extrapyramidal/opening_v_closing/door
# - extrapyramidal/recognize_small_object
- extrapyramidal/object_tracking/scramble/scramble_2_avocado
- extrapyramidal/object_tracking/scramble/scramble_3_avocado
- extrapyramidal/object_tracking/scramble/scramble_4_avocado
- extrapyramidal/object_tracking/scramble/scramble_2_chopsticks
- extrapyramidal/object_tracking/scramble/scramble_3_chopsticks
- extrapyramidal/object_tracking/scramble/scramble_4_chopsticks
- extrapyramidal/object_tracking/scramble/scramble_5_chopsticks
- extrapyramidal/object_tracking/scramble/scramble_2_potato
- extrapyramidal/object_tracking/scramble/scramble_3_potato
- extrapyramidal/object_tracking/scramble/scramble_4_potato
- extrapyramidal/object_tracking/scramble/scramble_2_tomato
- extrapyramidal/object_tracking/scramble/scramble_3_tomato
- extrapyramidal/object_tracking/scramble/scramble_4_tomato
- extrapyramidal/object_tracking/scramble/scramble_5_tomato
- level_2/permutation/permutation_level_2_group_1
- level_2/permutation/permutation_level_2_group_2
- level_2/permutation/permutation_level_2_group_3
- level_2/permutation/permutation_level_2_group_4
- level_2/permutation/permutation_level_2_group_5
- level_2/permutation/permutation_level_2_group_6
- level_2/permutation/permutation_level_2_group_7
- level_2/permutation/permutation_level_2_group_8
- level_3/permutation/permutation_level_3_group_1
- level_3/permutation/permutation_level_3_group_2
- level_3/permutation/permutation_level_3_group_3
- level_3/permutation/permutation_level_3_group_4
- level_3/permutation/permutation_level_3_group_5
- level_3/permutation/permutation_level_3_group_6
- level_3/permutation/permutation_level_3_group_7
- level_3/permutation/permutation_level_3_group_8
- level_5/permutation/permutation_level_5_group_1
- level_5/permutation/permutation_level_5_group_2
- level_5/permutation/permutation_level_5_group_3
- level_5/permutation/permutation_level_5_group_4
- level_5/permutation/permutation_level_5_group_5
task_dir: /data/datasets/vlm_benchmark/tasks/real_life
video_dir: /data/datasets/vlm_benchmark/videos/real_life
cache_dir: /data/datasets/vlm_benchmark/.cache
output_dir: /data/datasets/vlm_benchmark/experiments/evan