models:
- async_batch: false
  is_one_shot: true
  kind: gpt
  model: gpt-4o
  n_frames: 16
# - async_batch: false
#   is_one_shot: false
#   kind: gpt
#   model: gpt-4o
#   n_frames: 16
# - async_batch: false
#   is_one_shot: false
#   kind: gpt
#   model: gpt-4o
#   n_frames: 5
# - encoder: s3d
#   heads:
#   - kind: cosine
#   kind: encoder
# - encoder: viclip
#   heads:
#   - kind: cosine
#   kind: encoder
# - encoder: clip
#   heads:
#   - kind: cosine
#   hf_model: ViT-bigG-14/laion2b_s39b_b160k
#   kind: encoder
#   n_frames: 4
# - batch_size: 1
#   encoder: clip
#   heads:
#   - kind: cosine
#   hf_model: ViT-bigG-14/laion2b_s39b_b160k
#   kind: encoder
#   n_frames: 32
tasks:
# - extrapyramidal/object_tracking - not completed
# - extrapyramidal/opening_and_closing
# - extrapyramidal/recognize_small_object
- foundation/clean/apple
- foundation/clean/mug
# - foundation/containers/put_object/apple
# - foundation/containers/put_object/can
# - foundation/containers/put_object/hammer
# - foundation/containers/put_object/mug
# - foundation/cool - not completed
# - foundation/heat - not completed
# - foundation/objects/pick_from_counter_top - not completed
# - foundation/objects/pick_from_dining_table - not completed
# - foundation/on_v_off/desk_lamp
# - foundation/on_v_off/faucet
# - foundation/on_v_off/floor_lamp
# - foundation/on_v_off/microwave
# - foundation/pick_v_put/fork - not completed
# - foundation/pick_v_put other - not completed
# - foundation/toggle/desk_lamp
# - foundation/toggle/faucet
# - foundation/toggle/floor_lamp
# - foundation/toggle/microwave
# - foundation/slice/apple
# - foundation/slice/potato
# - foundation/sliced_v_whole/apple
# - foundation/sliced_v_whole/potato
video_dir: /data/datasets/vlm_benchmark/videos/alfred
task_dir: /data/datasets/vlm_benchmark/tasks/real_life
video_dir: /data/datasets/vlm_benchmark/videos/real_life
cache_dir: /data/datasets/vlm_benchmark/.cache
output_dir: /data/datasets/vlm_benchmark/experiments/evan
